In [11]:
import tensorflow as tf
from primePy import primes

## Point 1  
Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [66]:
random_tensor = tf.Variable(tf.random.normal([5,5]))
random_tensor

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[ 0.3796783 , -1.045349  , -0.24580678,  0.08919273, -0.5778024 ],
       [ 1.0997059 , -1.1201049 , -0.75265694, -0.9161868 , -0.63139653],
       [-0.14814107, -0.20744577, -1.003163  ,  1.7402698 ,  0.67406   ],
       [-0.33613265,  1.8068883 , -0.20871554,  0.6085208 ,  1.0634058 ],
       [-0.4753047 ,  0.81030756, -1.0491508 ,  1.1265503 ,  0.47061774]],
      dtype=float32)>

## Point 2  
Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [67]:
list_prime = primes.first(25)

for i in range(len(list_prime)-1):
    list_prime[i] *= 1.0

prime_tensor = tf.Variable(tf.convert_to_tensor(list_prime), dtype='float32')
prime_tensor = tf.reshape(prime_tensor, (5, 5))

prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

## Point 3  
Tampilkan dimensi dari kedua variable tersebut

In [209]:
print("Dimensi random_tensor adalah:", random_tensor.shape)
print("Dimensi prime_tensor adalah :", prime_tensor.shape)

Dimensi random_tensor adalah: (5, 5)
Dimensi prime_tensor adalah : (5, 5)


## Point 4  
Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

### Add

In [70]:
tf.add(prime_tensor, random_tensor).numpy()

array([[ 2.3796782,  1.954651 ,  4.7541933,  7.089193 , 10.422197 ],
       [14.099706 , 15.879895 , 18.247343 , 22.083813 , 28.368603 ],
       [30.851858 , 36.792553 , 39.996838 , 44.74027  , 47.67406  ],
       [52.663868 , 60.80689  , 60.791283 , 67.60852  , 72.06341  ],
       [72.5247   , 79.81031  , 81.95085  , 90.12655  , 97.47062  ]],
      dtype=float32)

### Subtract

In [71]:
tf.subtract(prime_tensor, random_tensor).numpy()

array([[ 1.6203218,  4.045349 ,  5.2458067,  6.910807 , 11.577803 ],
       [11.900294 , 18.120106 , 19.752657 , 23.916187 , 29.631397 ],
       [31.148142 , 37.207447 , 42.003162 , 41.25973  , 46.32594  ],
       [53.336132 , 57.19311  , 61.208717 , 66.39148  , 69.93659  ],
       [73.4753   , 78.18969  , 84.04915  , 87.87345  , 96.52938  ]],
      dtype=float32)

### Multiply

In [73]:
tf.multiply(prime_tensor, random_tensor).numpy()

array([[  0.7593566 ,  -3.136047  ,  -1.229034  ,   0.62434906,
         -6.3558264 ],
       [ 14.296177  , -19.041784  , -14.300482  , -21.072296  ,
        -18.3105    ],
       [ -4.5923734 ,  -7.6754937 , -41.12968   ,  74.831604  ,
         31.680819  ],
       [-17.815031  , 106.606415  , -12.731648  ,  40.770893  ,
         75.50181   ],
       [-34.697243  ,  64.0143    , -87.07952   , 100.26298   ,
         45.64992   ]], dtype=float32)

### Divide

In [74]:
tf.divide(prime_tensor, random_tensor).numpy()

array([[   5.267617,   -2.869855,  -20.34118 ,   78.481735,  -19.03765 ],
       [  11.821342,  -15.17715 ,  -25.243904,  -25.10405 ,  -45.92993 ],
       [-209.26    , -178.35986 ,  -40.870728,   24.708813,   69.72673 ],
       [-157.67584 ,   32.65282 , -292.26382 ,  110.10306 ,   66.76661 ],
       [-153.5857  ,   97.49384 ,  -79.1116  ,   79.00224 ,  206.11208 ]],
      dtype=float32)

### Matrix Multiplication

In [75]:
tf.matmul(prime_tensor, random_tensor).numpy()

array([[  -4.263511 ,   15.07336  ,  -20.767067 ,   22.782873 ,
          12.941141 ],
       [  -0.6987474,   28.48456  ,  -70.27659  ,   65.31539  ,
          32.668213 ],
       [   9.592341 ,   33.425674 , -134.88286  ,  119.33139  ,
          54.208397 ],
       [  19.701479 ,   44.449482 , -207.10112  ,  177.58463  ,
          77.90378  ],
       [  26.27722  ,   57.39613  , -281.00964  ,  242.00842  ,
         104.18011  ]], dtype=float32)

## Point 5  
Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [196]:
first = random_tensor[0][0].numpy()

max_list = tf.argmax(random_tensor, axis=1).numpy()
max_var = first

for i in range(0,5):
    a = tf.gather_nd(random_tensor,indices=[i])[max_list[i]].numpy()
    if (a > max_var):
        max_var = a

        
min_list = tf.argmin(random_tensor, axis=1).numpy()
min_var = first

for i in range(0,5):
    a = tf.gather_nd(random_tensor,indices=[i])[min_list[i]].numpy()
    if (a < min_var):
        min_var = a
    
print("Nilai max: ", max_var)
print("Nilai min: ", min_var)

Nilai max:  1.8068883
Nilai min:  -1.1201049


## Point 6  
Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [206]:
tf.concat([random_tensor, prime_tensor], axis=0).numpy()

array([[ 3.7967831e-01, -1.0453490e+00, -2.4580678e-01,  8.9192726e-02,
        -5.7780242e-01],
       [ 1.0997059e+00, -1.1201049e+00, -7.5265694e-01, -9.1618681e-01,
        -6.3139653e-01],
       [-1.4814107e-01, -2.0744577e-01, -1.0031630e+00,  1.7402698e+00,
         6.7405999e-01],
       [-3.3613265e-01,  1.8068883e+00, -2.0871554e-01,  6.0852081e-01,
         1.0634058e+00],
       [-4.7530469e-01,  8.1030756e-01, -1.0491508e+00,  1.1265503e+00,
         4.7061774e-01],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  6.7000000e+01,
         7.1000000e+01],
       [ 7.3000000e+01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
         9.7000000e+01]], dtype=float32)

## Point 7  
Tampilkan hasil sorting dari kedua variable di atas. (descending)

### 1. Random Tensor

In [202]:
tf.sort(random_tensor, direction="DESCENDING").numpy()

array([[ 0.3796783 ,  0.08919273, -0.24580678, -0.5778024 , -1.045349  ],
       [ 1.0997059 , -0.63139653, -0.75265694, -0.9161868 , -1.1201049 ],
       [ 1.7402698 ,  0.67406   , -0.14814107, -0.20744577, -1.003163  ],
       [ 1.8068883 ,  1.0634058 ,  0.6085208 , -0.20871554, -0.33613265],
       [ 1.1265503 ,  0.81030756,  0.47061774, -0.4753047 , -1.0491508 ]],
      dtype=float32)

### 2. Prime Tensor

In [205]:
tf.sort(prime_tensor, direction="DESCENDING").numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)